# Generated by Django 2.2.22 on 2022-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ig_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Username'),
        ),
    ]
