# Generated by Django 2.2.22 on 2022-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220114_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_3',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=255, null=True, verbose_name='language'),
        ),
    ]
