# Generated by Django 2.2.22 on 2022-01-28 08:34

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('profile_photo', app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='reference_pic')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('reference_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_for_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
