# Generated by Django 2.2.22 on 2022-01-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220128_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ddf/'),
        ),
    ]
