# Generated by Django 2.2.22 on 2022-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220128_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
