# Generated by Django 2.2.22 on 2022-02-02 01:00

import app.models
from django.db import migrations
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220201_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='profile_photo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='reference_pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='profile_pic'),
        ),
    ]
