# Generated by Django 2.2.22 on 2022-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_referencerequestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequestid',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
