# Generated by Django 2.2.22 on 2022-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20220221_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='about business'),
        ),
    ]
