# Generated by Django 2.2.22 on 2022-02-22 22:25

import app.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20220222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='about business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='profile_pic'),
        ),
    ]
