# Generated by Django 2.2.22 on 2022-02-24 07:02

import app.models
from django.db import migrations
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20220223_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='profile_pic'),
        ),
    ]
