# Generated by Django 2.2.22 on 2022-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20220224_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_added',
            field=models.BooleanField(default=False),
        ),
    ]
