# Generated by Django 2.2.22 on 2022-03-31 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_reference_reference_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed', to=settings.AUTH_USER_MODEL)),
                ('user_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
