# Generated by Django 2.2.22 on 2022-03-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_profileview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileView',
            new_name='ProfileViewModel',
        ),
    ]
