# Generated by Django 2.2.22 on 2022-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20220331_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='reference_added',
        ),
        migrations.AddField(
            model_name='referencerequestid',
            name='reference_added',
            field=models.BooleanField(default=False),
        ),
    ]
