# Generated by Django 2.2.22 on 2022-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20220331_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencerequestid',
            name='reference_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
