# Generated by Django 2.2.22 on 2021-10-20 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('contract_name', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('summary', models.TextField(max_length=500)),
                ('payment_included', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'In Progress'), (4, 'Completed'), (5, 'Canceled'), (6, 'Dispute'), (7, 'Rejected')], default=1)),
                ('contract_completed_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_contract_type', to='contracts.ContractTypeModel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('created_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_with_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'create_contract',
            },
        ),
    ]
