# Generated by Django 2.2.22 on 2021-11-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelContractReasonChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cancel Contract Reason Choice',
                'verbose_name_plural': 'Cancel Contract Reason Choices',
            },
        ),
        migrations.CreateModel(
            name='EndContractReasonChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'End Contract Reason Choice',
                'verbose_name_plural': 'End Contract Reason Choices',
            },
        ),
        migrations.CreateModel(
            name='RejectContractReasonChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Reject Contract Reason Choice',
                'verbose_name_plural': 'Reject Contract Reason Choices',
            },
        ),
        migrations.CreateModel(
            name='ContractCloseFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('status', models.SmallIntegerField(choices=[(1, 'Reject Contract'), (2, 'End Contract'), (3, 'Cancel Contract')])),
                ('feedback', models.TextField(blank=True, max_length=200, null=True)),
                ('rating', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('cancel_contract_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.CancelContractReasonChoiceModel')),
                ('end_contract_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.EndContractReasonChoiceModel')),
                ('reject_contract_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.RejectContractReasonChoiceModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
