# Generated by Django 2.2.22 on 2021-11-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20211101_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclosefeedback',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.ContractsModel'),
            preserve_default=False,
        ),
    ]
