# Generated by Django 2.2.22 on 2021-11-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contractclosefeedback_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractclosefeedback',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_feedback', to='contracts.ContractsModel'),
        ),
    ]
