# Generated by Django 2.2.22 on 2021-12-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contracttemplates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractTemplates',
            new_name='ContractTemplate',
        ),
    ]
