# Generated by Django 2.2.22 on 2021-12-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20211216_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='tag',
            field=models.ManyToManyField(to='contracts.ContractTemplateTag'),
        ),
    ]
