# Generated by Django 2.2.22 on 2021-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20211217_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contracttemplatetag',
            name='tag',
            field=models.CharField(max_length=40),
        ),
    ]
