# Generated by Django 2.2.22 on 2021-12-22 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0010_auto_20211217_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='agreement',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('receiving_party_email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('initail_amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'In Progress'), (4, 'Completed'), (5, 'Canceled'), (6, 'Dispute'), (7, 'Rejected')], default=1)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_type', to='contracts.ContractTemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
