# Generated by Django 2.2.22 on 2022-01-03 16:26

import app.models
from django.db import migrations
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_auto_20220102_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='logo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='contract_image'),
        ),
    ]
