# Generated by Django 2.2.22 on 2022-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_auto_20220103_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
