# Generated by Django 2.2.22 on 2022-03-10 16:30

import app.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_contracttemplate_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsmodel',
            name='created_with_email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='logo',
            field=app.models.S3ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='contract_image'),
        ),
    ]
