# Generated by Django 2.2.22 on 2021-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211115_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(default='test02@chatscrum.com', max_length=500),
        ),
    ]
