# Generated by Django 2.2.22 on 2022-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_maillmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillmessage',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
