# Generated by Django 2.2.22 on 2022-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220122_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(default='default from email', max_length=500),
        ),
    ]
