# Generated by Django 2.2.22 on 2022-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220122_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
