# Generated by Django 2.2.22 on 2022-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_allsearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillmessage',
            name='group',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'INCOMPLETE_REGISTRANT'), (2, 'COMPLETE_REGISTRANT_WITH_REFERENCE'), (3, 'COMPLETE_REGISTRANT_WITHOUT_REFERENCE')], null=True),
        ),
        migrations.AddField(
            model_name='maillmessage',
            name='send_it',
            field=models.BooleanField(default=False),
        ),
    ]
