# Generated by Django 2.2.22 on 2022-03-29 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20220328_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsearches',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
