apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: justeeceapp
  name: justeecedeploy
  namespace: justeece
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: justeeceapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: justeeceapp
    spec:
      containers:
      - name: intjusteece
        env:
        - name: WORDPRESS_DB_HOST
          value: newklj-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: 1qaz#EDC3edc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        #name: lwt
        ports:
        - containerPort: 8000
          name: port40
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /justeece/justeece/settings.py
          name: justeece-settings
      imagePullSecrets:
      - name: gitlab-regcred
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /opt/dockermounts/settings_justeece.py
          type: File
        name: justeece-settings
