apiVersion: v1
kind: Service
metadata:
  labels:
    app: justeeceapp
  name: justeece-svc
  namespace: justeece
spec:
  ports:
  - name: port8000
    nodePort: 31801
    port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    app: justeeceapp
  type: NodePort
